export const destinations = [
  { label: "김포", value: "GMP", country: "대한민국" },
  { label: "김해", value: "PUS", country: "대한민국" },
  { label: "제주", value: "CJU", country: "대한민국" },
  { label: "괌", value: "GUM", country: "미국" },
  { label: "광저우", value: "CAN", country: "중국" },
  { label: "나리타", value: "NRT", country: "일본" },
  { label: "뉴욕", value: "JFK", country: "미국" },
  { label: "도쿄", value: "HND", country: "일본" },
  { label: "두바이", value: "DXB", country: "아랍에미리트" },
  { label: "라스베이거스", value: "LAS", country: "미국" },
  { label: "로마", value: "FCO", country: "이탈리아" },
  { label: "마닐라", value: "MNL", country: "필리핀" },
  { label: "멜버른", value: "MEL", country: "호주" },
  { label: "방콕", value: "BKK", country: "태국" },
  { label: "베이징", value: "PEK", country: "중국" },
  { label: "샌프란시스코", value: "SFO", country: "미국" },
  { label: "싱가포르", value: "SIN", country: "싱가포르" },
  { label: "오사카", value: "KIX", country: "일본" },
  { label: "울란바토르", value: "ULN", country: "몽골" },
  { label: "자카르타", value: "CGK", country: "인도네시아" },
  { label: "주하이", value: "ZUH", country: "중국" },
  { label: "청두", value: "CTU", country: "중국" },
  { label: "치앙마이", value: "CNX", country: "태국" },
  { label: "쿠알라룸푸르", value: "KUL", country: "말레이시아" },
  { label: "카트만두", value: "KTM", country: "네팔" },
  { label: "타이베이", value: "TPE", country: "대만" },
  { label: "토론토", value: "YYZ", country: "캐나다" },
  { label: "파리", value: "CDG", country: "프랑스" },
  { label: "프놈펜", value: "PNH", country: "캄보디아" },
  { label: "하노이", value: "HAN", country: "베트남" },
  { label: "홍콩", value: "HKG", country: "홍콩" },
  
];
